export * as def from '@assets/styles/default'
export * as hero from '@assets/styles/hero-carousel'
export * as modal from '@assets/styles/modal'
export * as form from '@assets/styles/form'
export * as nav from '@assets/styles/navbar'
export * as product from '@assets/styles/product'
export * as search from '@assets/styles/searchbar'
export * as productPage from '@assets/styles/product-page'
export { default as ANIMATE } from '@assets/styles/animations-settings'
